# https://ci.appveyor.com/project/MS-Astra/qt4
---
branches:
  only:
  - 4.8
  
clone_depth: 5 

# just perform builds for now, don't run tests
build_script:
    - cmd: configure.exe -debug -platform win32-msvc2013
    - cmd: nmake.exe
